### ISSUE TITLE
Using Rupture with create-react-app

### ISSUE THREAD

**Issue by crs1138** [jescalan/rupture#85] opened 2018-08-22 16:09 UTC
I wonder if anybody could help me out here… I've got a ReactJS project, I made the app using the `create-react-app` and I'm using `stylus`. I'd like to add the `rupture` module to take care of the media queries.  I have installed rupture to the project via `yarn add rupture --dev`. But how do I _import_ it? I've tried to import it into my main style.styl: `@require '~rupture/rupture/index.styl` That gives me:
```
Error: src/static/stylus/style.styl:7:10
   3|  * This file shall not contain any declaration, only requires
   4|  * and imports
   5|  */
   6|
   7| @require '~rupture/rupture/index.styl'
---------------^
   8| @require 'partials/*'

failed to locate @require file ~rupture/rupture/index.styl
```

I've tried the command line equivalent in a yarn script: `"watch-css": "yarn build-css && ./node_modules/stylus/bin/stylus --use ./node_modules/rupture/rupture/index.styl -c -w src/static/stylus/ --out src/static/css",` but that throws the following error
```
    8| rupture.scale = 0 576px 768px 992px 1200px 1800px
--------------^
    9| rupture.scale-names = 'xs' 'sm' 'md' 'lg' 'xl' 'hd'
   10| rupture.enable-em-breakpoints = true
   11| rupture.anti-overlap = -1px

rupture has no property .scale
```
Here's my package.json in case you need it…
```
{
  "name": "xyz.com",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.1.3",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-scripts": "1.1.4",
    "stylus": "^0.54.5"
  },
  "scripts": {
    "build-css": "./node_modules/stylus/bin/stylus -c src/static/stylus/ --out src/static/css",
    "watch-css": "yarn build-css && ./node_modules/stylus/bin/stylus --use ./node_modules/rupture/rupture/index.styl -c -w src/static/stylus/ --out src/static/css",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "jquery": "^3.3.1",
    "npm-run-all": "^4.1.3",
    "popper.js": "^1.14.4",
    "rupture": "^0.7.1"
  }
}
```

**Comment by jescalan** [comment] 2018-08-22 18:19
What is the tilde before the require? That doesn't seem like a valid path. You'd need to get the correct path, which likely means going into `node_modules`. You could also include it in your stylus config as a plugin as demonstrated in the [usage section](https://github.com/jescalan/rupture#usage)

**Comment by crs1138** [comment] 2018-08-22 19:23
The tilde should resolve as {}/node_modules. It's the recommended way used by other modules. For example animate.css, normalize.css and others. Here's a mention of it https://github.com/webpack-contrib/css-loader/issues/12#issuecomment-41940311

**Comment by jescalan** [comment] 2018-08-22 19:27
Welp, as indicated by your error, it's not resolving that way for you 😕

**Comment by crs1138** [comment] 2018-08-22 19:31
Any other ideas, how to get your awesome/brilliant/excellent package to work with the ReactJS app that's been created via create-react-app?

**Comment by jescalan** [comment] 2018-08-22 19:53
Perhaps try using the actual path to resolve the module? I mean, this question is not really about rupture, it's about create-react-app and its stylus config. Rupture is just a stylus file, you can add it the same way you'd add any other stylus file. The problem is that you are unable to get the path to resolve through a webpack config, not that there's anything that could change with the stylus file itself. I added an idea above as well about including it as a stylus plugin for whatever the stylus config is for create-react-app.

I don't use create-react-app, and to be honest never intend to, so I am just not the expert you're after here - asking for help from people that use create-react-app with stylus will probably get you better results.

**Comment by crs1138** [comment] 2018-08-22 19:57
I don't get that examle, if that's what you mean…
```

stylus(fs.readFileSync('./example.styl', 'utf8'))
  .use(rupture())
  .render(function (err, css) {
    if (err) return console.error(err);
    console.log(css);
  });
```
produces

```
./src/index.js
  Line 12:  'fs' is not defined  no-undef
```

**Comment by crs1138** [comment] 2018-08-22 20:01
I got it working via `@require '../../../node_modules/rupture/rupture/index'`, but that's for my specific setup.

**Comment by jescalan** [comment] 2018-08-22 20:07
So it sounds like the tilde was not working as expected, like we guessed. I think we're now fully in the realm of webpack configuration errors, so this is out of range for this issue. Will try to help if I can, but going to close for now.

**Closed as completed by jescalan** 2018-08-22 20:07 UTC
